// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt24-lK3HMmW08Up7pXo21urWgw615r7M',
    appId: '1:209222226101:web:c06794408b47e767fa6efc',
    messagingSenderId: '209222226101',
    projectId: 'fire-test-fabio',
    authDomain: 'fire-test-fabio.firebaseapp.com',
    storageBucket: 'fire-test-fabio.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBLV1YMNtxEvfjRQmhMmheJTUeQUkjis0',
    appId: '1:209222226101:android:4dc740fd4c67d521fa6efc',
    messagingSenderId: '209222226101',
    projectId: 'fire-test-fabio',
    storageBucket: 'fire-test-fabio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPprzL2Rye8rhYHehbwGlTmz4Jz9ZKsws',
    appId: '1:209222226101:ios:c63e6f006f27ed31fa6efc',
    messagingSenderId: '209222226101',
    projectId: 'fire-test-fabio',
    storageBucket: 'fire-test-fabio.appspot.com',
    androidClientId: '209222226101-ip7cf6i263k17t367oeet6pa39e3gd24.apps.googleusercontent.com',
    iosClientId: '209222226101-ntvmv3tqod0skrjauagv5b10rbg04ajq.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPprzL2Rye8rhYHehbwGlTmz4Jz9ZKsws',
    appId: '1:209222226101:ios:9931897c09f89590fa6efc',
    messagingSenderId: '209222226101',
    projectId: 'fire-test-fabio',
    storageBucket: 'fire-test-fabio.appspot.com',
    androidClientId: '209222226101-ip7cf6i263k17t367oeet6pa39e3gd24.apps.googleusercontent.com',
    iosClientId: '209222226101-o9l716fa2l3vqvhnlios2e8j260997q3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireTest.RunnerTests',
  );
}
